version: "3"
services:
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=MINIO_ID
      - MINIO_SECRET_KEY=MINIO_KEY
    volumes:
      - ./files:/export
    command: minio server /export
    networks:
      - minionet
  backend:
    build: ./backend
    tty: true
    ports:
      - "10202:10202"
    environment:
      - LISTEN=:10202
    networks:
      - minionet
  backend1:
    build: ./backend1
    tty: true
    ports:
      - "10201:10201"
    environment:
      - LISTEN=:10201
  backend2:
    build: ./backend2
    tty: true
    ports:
      - "10200:10200"
    environment:
      - LISTEN=:10200
networks:
  minionet:
